### ISSUE TITLE
Build ionicons error

### ISSUE THREAD

**Issue by njleonzhang** [driftyco/ionicons#334]
Here is the log:

```
$ python ./builder/generate.py

Generate Fonts
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 17:27 PDT 28-Aug-2015-D.
 Based on source from git with hash:
Load Manifest, Icons: 734
Source files unchanged, did not rebuild fonts
Traceback (most recent call last):
  File "./builder/generate.py", line 318, in <module>
    main()
  File "./builder/generate.py", line 19, in main
    rename_svg_glyph_names(data)
  File "./builder/generate.py", line 45, in rename_svg_glyph_names
    svg_text = svg_text.replace(org_name, ion_name)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 375: ordinal not in range(128)
```

**Comment by njleonzhang** [comment]
I workaround the issue:
 
```
import sys 
```

set encoding in rename_svg_glyph_names
```
def rename_svg_glyph_names(data):
  # hacky and slow (but safe) way to rename glyph-name attributes
  svg_path = os.path.join(FONTS_FOLDER_PATH, 'ionicons.svg')
  svg_file = open(svg_path, 'r+')
  svg_text = svg_file.read()
  svg_file.seek(0)
  
  reload(sys)
  sys.setdefaultencoding("ISO-8859-1")

  for ionicon in data['icons']:
    # uniF2CA
    org_name = 'uni%s' % (ionicon['code'].replace('0x', '').upper())
    ion_name = 'ion-%s' % (ionicon['name'])
    print org_name
    print ion_name
    svg_text = svg_text.replace(org_name, ion_name)

  svg_file.write(svg_text)
  svg_file.close()
```

**Comment by adamdbradley** [comment]
Sorry but I'm unable to replicate this issue. So is it the `sys.setdefaultencoding("ISO-8859-1")` that fixes the issue? Do you know why that would be?

**Comment by njleonzhang** [comment]
@adamdbradley, I am not sure about the root cause, but I think this may be related to the os language. I am in China, so my os language is Chinese.

**Comment by liamdebeasi** [comment]
Hi everyone,

Thanks for the report and apologies for the delay. I am going to close as there is not enough information for us to verify this bug. If this is still a problem with the latest version of Ionicons, please reply to this thread with a GitHub repo that we can use to verify the reported behavior.
